import Head from "next/head";
import styles from "../styles/Container.module.scss";

import NextLink from "next/link";
import { useState } from "react";
import MobileMenu from "./MobileMenu";

export default function Container({children}) {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.navigation_wrapper}>
        <nav className={styles.navigation}>
          <div>
              <MobileMenu/>
            <NextLink className={styles.top_bar_listItem} href="/">
              Home
            </NextLink>
            <NextLink className={styles.top_bar_listItem} href="/">
              Get in touch
            </NextLink>
          </div>
        </nav>
      </div>
      <main className={styles.main_wrapper}>
        {children}
      </main>
    </div>
  );
}
